#!/bin/sh

if [ $(pgrep "polybar" | wc -l) -lt 2 ]; then
    killall polybar
    polybar bsp &
    polybar bsp_ext &
    sleep 0.2
fi

bspc monitor DP-1 -d 3 6 9
bspc monitor DP-1-2 -d 1 2 4 5 7 8 10

bspc desktop 6 -l monocle
bspc desktop 2 -l monocle

bspc config border_width         2
bspc config window_gap          2
bspc config bottom_padding          -2
bspc config left_padding          -2
bspc config right_padding          -2
bspc config top_padding          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config honor_size_hints    true


bspc config external_rules_command "$HOME/.config/bspwm/bspwm-rules"

# for compatibility with java applications like intellij-idea
wmname LG3D
