[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "Z", mods = "Control|Shift", command = { program = "zed", args = ["-n", "."] } },
    { key = "NumpadEnter", chars = "\r" },
]

[window]
decorations = "None"
opacity = 0.9

[scrolling]
history = 100000

# This is the default config but it addes the Shift mod for mouse click
[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.mods = "Shift"
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"


# Colors (Base16 Default Dark)

# Default colors
[colors.primary]
background = '#181818'
foreground = '#d8d8d8'

[colors.cursor]
text = '#181818'
cursor = '#d8d8d8'

# Normal colors
[colors.normal]
black = '#181818'
red = '#ab4642'
green = '#a1b56c'
yellow = '#f7ca88'
blue = '#7cafc2'
magenta = '#ba8baf'
cyan = '#86c1b9'
white = '#d8d8d8'

# Bright colors
[colors.bright]
black = '#585858'
red = '#ab4642'
green = '#a1b56c'
yellow = '#f7ca88'
blue = '#7cafc2'
magenta = '#ba8baf'
cyan = '#86c1b9'
white = '#f8f8f8'
