name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Perform a dry run without actually building"
        required: false
        default: "true"
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ["nixos-musholic-stream"]
    env:
      DRY_RUN: "${{ github.event.inputs.dry_run || 'false' }}"
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix build .#nixosConfigurations.${{matrix.config}}.config.system.build.toplevel $([[ $DRY_RUN == "true" ]] && echo "--dry-run")
