name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-zed:
    runs-on: ubuntu-latest
    steps:
      - name: Disable man-db to make package install and removal faster
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate >/dev/null
          sudo dpkg-reconfigure man-db
      - uses: actions/checkout@v4
      - name: free up disk space
        run: .github/scripts/free-disk-space-linux.sh
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: musholic
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      # Build Zed with resource limits to avoid being killed by Github
      - name: Build Zed with limited resources
        run: nix build --accept-flake-config --impure --expr "(builtins.getFlake \"$PWD\").inputs.zed-preview.packages.x86_64-linux.default"

  build-and-diff:
    runs-on: ubuntu-latest
    needs: build-zed
    strategy:
      matrix:
        config: ["nixos-musholic-stream"]
    outputs:
      config: ${{ matrix.config }}
    steps:
      - name: Disable man-db to make package install and removal faster
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate >/dev/null
          sudo dpkg-reconfigure man-db
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: free up disk space
        run: .github/scripts/free-disk-space-linux.sh
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: musholic
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: DeterminateSystems/flake-checker-action@main

      # Build and evaluate current commit
      - name: Nix Build Current
        run: nix build --accept-flake-config .#nixosConfigurations.${{matrix.config}}.config.system.build.toplevel $([[ $DRY_RUN == "true" ]] && echo "--dry-run")
      - name: Nix Eval Current
        run: nix eval --accept-flake-config .#nixosConfigurations.${{matrix.config}}.config.system.build.toplevel --raw > eval_current.txt

      # Build and evaluate parent commit (reuses Nix store paths)
      - name: Checkout parent commit
        run: git checkout ${{ github.event.pull_request.base.sha || 'HEAD^' }}
      - name: Nix Build Parent
        run: nix build --accept-flake-config .#nixosConfigurations.${{matrix.config}}.config.system.build.toplevel $([[ $DRY_RUN == "true" ]] && echo "--dry-run")
      - name: Nix Eval Parent
        run: nix eval --accept-flake-config .#nixosConfigurations.${{matrix.config}}.config.system.build.toplevel --raw > eval_parent.txt

      # Generate diff using nvd
      - name: Install nvd
        run: nix-env -i nvd -f '<nixpkgs>'
      - name: Generate nvd diff
        run: |
          current_eval=$(cat eval_current.txt)
          parent_eval=$(cat eval_parent.txt)
          nvd diff "$parent_eval" "$current_eval" | tee nvd_diff.txt

      - name: Create diff report
        run: |
          cat > nvd_diff_report.md << EOF
          ## Nvd Diff Report

          <details>
          <summary>Package Changes</summary>

          \`\`\`
          $(cat nvd_diff.txt)
          \`\`\`

          </details>
          EOF

      - name: Add diff report to step summary
        run: |
          cat nvd_diff_report.md >> $GITHUB_STEP_SUMMARY

      - name: Upload diff report
        uses: actions/upload-artifact@v4
        with:
          name: nvd-diff-${{ matrix.config }}
          path: nvd_diff_report.md

  validate-and-comment:
    if: github.event_name == 'pull_request'
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: build-and-diff
    steps:
      - name: Download diff
        uses: actions/download-artifact@v4
        with:
          name: nvd-diff-${{ needs.build-and-diff.outputs.config }}

      - name: Fail if no actual changes
        if: github.head_ref == 'update_flake_lock_action'
        run: |
          if grep -q "No version or selection state changes" nvd_diff_report.md; then
            echo "::error::No package changes between commits"
            exit 1
          else
            echo "Package changes found"
          fi

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Find existing Nvd diff comment
        uses: peter-evans/find-comment@v3
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "## Nvd Diff Report"

      - name: Post Nvd Diff
        uses: peter-evans/create-or-update-comment@v4
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: nvd_diff_report.md
          edit-mode: replace
